export enum ToolbarItemKeyEnum {
    DASHBOARD = 'DASHBOARD',
    AGENDAR_POST = 'AGENDAR_POST',
    CALENDAR = 'CALENDAR',
    INBOX = 'INBOX',
    FEED = 'FEED',
    WORKFLOW = 'WORKFLOW',
    ACOMPANHAMENTO = 'ACOMPANHAMENTO',
    RELATORIOS = 'RELATORIOS',
}
